Update azure-pipelines.yaml for Azure Pipelines

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -107,7 +107,15 @@ stages:
               inlineScript: |
                 openssl pkcs8 -topk8 -in csr.key -out keynew.pem -nocrypt
                 cat keynew.pem >> certificate_chain.pem
-                az keyvault certificate import --vault-name $(KEY_VAULT_NAME) -n $(KEY_VAULT_CERT_NAME) --disabled false -f certificate_chain.pem
+                RESULT=$(az keyvault certificate import --vault-name $(KEY_VAULT_NAME) -n $(KEY_VAULT_CERT_NAME) --disabled false -f certificate_chain.pem)
+                if [ $? -eq 0 ]
+                then
+                  echo "certificate imported"
+                  exit 0
+                else
+                  echo "error certificate not imported"
+                  exit 1
+                fi
           - task: Bash@3
             name: clean_up
             condition: succeededOrFailed()
