test pkcs12

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -27,14 +27,16 @@ stages:
                 if [ ${{ parameters.force_renew_cert }} == "True" ]
                 then
                   echo "##vso[task.setvariable variable=require_new_certificate;isOutput=true]True"
+                  echo "Parameter force_renew_cert is set to true"
                   exit 0
                 fi
-                if ! az keyvault certificate download --vault-name '$(KEY_VAULT_NAME)' -n '$(KEY_VAULT_CERT_NAME)' -f certificate.pem
+                if ! az keyvault certificate download --vault-name '$(KEY_VAULT_NAME)' -n '$(KEY_VAULT_CERT_NAME)' -f certificate.pfx >/dev/null
                 then
                   echo "##vso[task.setvariable variable=require_new_certificate;isOutput=true]True"
+                  echo "The certificate was not found in the selected keyvault"
                   exit 0
                 else
-                  if ! openssl x509 -checkend '$(CERT_NAME_EXPIRE_SECONDS)' -noout -in certificate.pem >/dev/null 2>&1
+                  if ! openssl x509 -inform pem -checkend '$(CERT_NAME_EXPIRE_SECONDS)' -noout -in <(openssl pkcs12 -in certificate.pfx -clcerts -passin pass: -passout pass: 2>/dev/null)
                   then
                     # certificate is expiring or is already expired
                     echo "##vso[task.setvariable variable=require_new_certificate;isOutput=true]True"
