Update azure-pipelines.yaml for Azure Pipelines

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -35,22 +35,29 @@ stages:
 
                 echo "get certificate from keyvault"
                 RESULT=$(az keyvault certificate download --vault-name $(KEY_VAULT_NAME) -n $(KEY_VAULT_CERT_NAME) -f cert.pem)
-
                 if [ $? -eq 0 ]
                 then
                   echo "certificate found, test expire date"
-                  if openssl x509 -checkend $(CERT_NAME_EXPIRE_SECONDS) -noout -in cert.pem
-                  then
-                    echo "expire date is greater then CERT_NAME_EXPIRE_SECONDS"
-                    echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]False"
-                  else
-                    echo "expire date is less then CERT_NAME_EXPIRE_SECONDS, , create new certificate"
-                    echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
-                  fi
                 else
                   echo "certificate not found, create new certificate"
                   echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
                 fi
+                
+                # if [ $? -eq 0 ]
+                # then
+                #   echo "certificate found, test expire date"
+                #   if openssl x509 -checkend $(CERT_NAME_EXPIRE_SECONDS) -noout -in cert.pem
+                #   then
+                #     echo "expire date is greater then CERT_NAME_EXPIRE_SECONDS"
+                #     echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]False"
+                #   else
+                #     echo "expire date is less then CERT_NAME_EXPIRE_SECONDS, , create new certificate"
+                #     echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
+                #   fi
+                # else
+                #   echo "certificate not found, create new certificate"
+                #   echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
+                # fi
             # associate Service Connection, retrieve only Certificates
             # Python to return if expired on timedelta variable
             # serviceconnection: $(serviceconnection)
